package com.example.omat.students;

public enum Faculty {
    MATH_INFORMATICS,
    BUSINESS_SCHOOL,
    CHEMISTRY_GEOSCIENCES,
    COMMUNICATION,
    ECONOMICS_BUSINESS_ADMINISTRATION,
    HISTORY,
    LAW,
    MEDICINE,
    PHILOLOGY,
    PHILOSOPHY,
    PHYSICS
}
